<?php
namespace Mokos\Generator;

require_once dirname(__FILE__) . '/../../../src/Generator/DaoGenerator.php';

/**
 * Test class for DaoGenerator.
 * Generated by PHPUnit on 2012-11-03 at 04:32:44.
 */
class DaoGeneratorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DaoGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $template = dirname(__FILE__) . '/../../../src/Template/DAO_IMPL.tpl';
        $file = dirname(__FILE__);
        $this->object = new DaoGenerator($template,$file,new \Mokos\Database\Table\AdapterMysql());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGenerate().
     */
    public function testGenerate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
